#SERVER CONSTANTS
CONNECTED = 4
DISCONNECTED = 2
ACCOUNT_CREATED = 3
OPPONENT_CONNECTED = 20
OPPONENT_DISCONNECTED = 21
RECONNECTION = 22
# GAME_UPDATES
USER_SHIP_PLACEMENT = 40
OPPONENT_SHIP_PLACEMENT	= 41
SHOTS_FIRED_BY_USER = 42
SHOTS_FIRED_BY_OPPONENT = 43
SHOT_FIRED_BY_OPPONENT = 44
TURN = 45

#CLIENT CONSTANTS
LOGIN = 1
LOGOUT = 2
SIGNUP = 3
CONNECT_WITH_OPPONENT = 20
DISCONNECT_WITH_OPPONENT = 21
RECONNECT_WITH_OPPONENT = 22
# GAME_UPDATES
SHIP_PLACEMENT_UPDATE = 40
SHOT_FIRED = 42
